apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: LoadBalancer
  selector:
    app: zookeeper-label
  ports:
  - port: 42100
    targetPort: zookeeper-port
    protocol: TCP
