apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-apply-cluster-role
rules:
  - apiGroups:
      [
        "",
        "extensions",
        "apps",
        "rbac.authorization.k8s.io",
        "roles.rbac.authorization.k8s.io",
        "batch"
      ]
    resources:
      [
        "deployments",
        "rolebindings",
        "roles",
        "services",
        "serviceaccounts",
        "configmaps",
        "persistentvolumes",
        "persistentvolumeclaims",
        "clusterrolebindings",
        "clusterroles",
        "cronjobs"
      ]
    verbs: ["create", "update", "delete", "get", "patch"]
