apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-ui
  template:
    metadata:
      labels:
        app: streaming-ui
    spec:    
      containers:
        - name: streaming-ui
          image: natery2000/streaming-ui:1.0.3
          ports:
            - name: str-ui-port
              containerPort: 4000