apiVersion: v1
kind: Service
metadata:
  name: streaming-ui-service
spec:
  type: LoadBalancer
  selector:
    app: streaming-ui-label
  ports:
    - port: 4200
      targetPort: 4000
      protocol: TCP