apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-label
  template:
    metadata:
      labels:
        app: schema-registry-label
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.0.1
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "localhost"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "kafka-service:42001"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:30081"
          ports:
            - containerPort: 30081
              name: schema-reg-port