apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
spec:
  type: LoadBalancer
  selector:
    app: schema-registry-label
  ports:
  - name: schema-reg-port
    port: 42200
    targetPort: schema-reg-port
    protocol: TCP
