apiVersion: v1
kind: Service
metadata:
  name: game-session-service
spec:
  type: LoadBalancer
  selector:
    app: game-session-label
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      nodePort: 32001