apiVersion: apps/v1
kind: Deployment
metadata:
  name: poe-aura-optimizer-deployment

spec:
  replicas: 0
  selector:
    matchLabels:
      app: poe-aura-optimizer-label
  template:
    metadata:
      labels:
        app: poe-aura-optimizer-label
    spec:    
      containers:
        - name: poe-aura-optimizer
          image: natery2000/poe-aura-optimizer:1.0.9
          ports:
            - containerPort: 4000