apiVersion: apps/v1
kind: Deployment
metadata:
  name: poe-aura-optimizer

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:    
      containers:
        - name: poe-aura-optimizer
          image: natery2000/poe-aura-optimizer
          ports:
            - containerPort: 4000