apiVersion: v1
kind: Service
metadata:
  name: poe-aura-optimizer-service
spec:
  type: LoadBalancer
  selector:
    app: poe-aura-optimizer
  ports:
    - port: 40000
      targetPort: pao-port
      protocol: TCP