apiVersion: v1
kind: Service
metadata:
  name: poe-aura-optimizer-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      nodePort: 31000