apiVersion: v1
kind: Service
metadata:
  name: poe-aura-optimizer-service
spec:
  type: LoadBalancer
  selector:
    app: poe-aura-optimizer-label
  ports:
    - port: 4000
      targetPort: poe-aura-optimizer-port
      protocol: TCP