apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-couchdb-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-couchdb
  template:
    metadata:
      labels:
        app: streaming-couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb
          imagePullPolicy: Always
          ports:
          - name: st-couchdb-port
            containerPort: 5984
          volumeMounts:
          - name: streaming-couchdb-volume
            mountPath: /var/lib/couchdb
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: password
      volumes:
        - name: streaming-couchdb-volume
          persistentVolumeClaim:
            claimName: streaming-couchdb-pvc