apiVersion: v1
kind: PersistentVolume
metadata:
  name: streaming-couchdb-pv
  labels:
    volume-type: couchdb
spec:
  capacity:
   storage: 2Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: couchdb-storageclass
  hostPath:
    path: /run/desktop/mnt/host/c/dockerdesktop/volumes/couchdb-streaming
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop