apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-couchdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: streaming-couchdb-pv
  storageClassName: couchdb-storageclass