apiVersion: v1
kind: Service
metadata:
  name: streaming-couchdb-service
spec:
  type: LoadBalancer
  selector:
    app: streaming-couchdb
  ports:
  - port: 41000
    targetPort: st-couchdb-port
    protocol: TCP
